from .auth import *
from .dashboard import *
from .employees import *
from .hospitals import *
from .doctors import *
from .visits import *
from .claims import *
from .bills import *
from .finance import *
from .inventory import *
from .procurement import *
from .reports import *
from .search import *
from .users import *
from .notifications_views import *
from .audit import *
