# Generated by Django 6.1 on 2026-08-30 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('father_name', models.CharField(blank=True, max_length=120, null=True)),
                ('department', models.CharField(max_length=120)),
                ('designation', models.CharField(blank=True, max_length=120, null=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_date', models.DateField()),
                ('hospital', models.CharField(max_length=200)),
                ('doctor', models.CharField(blank=True, max_length=120, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lab_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medicine_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('admission_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bill_no', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Processed', 'Processed'), ('Pending', 'Pending')], default='Paid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='welfare_app.employee')),
            ],
        ),
    ]
