# Generated by Django 6.1.1 on 2026-09-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0002_department_hospital_medicine_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='grade_scale',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
