# Generated by Django 6.1.1 on 2026-09-18 07:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0003_alter_employee_contact_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-bill_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-year', 'department__name']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='financetransaction',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='hospitalvisit',
            options={'ordering': ['-visit_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='medicalclaim',
            options={'ordering': ['-claim_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='medicinetransaction',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='category',
            field=models.CharField(choices=[('Doctor Fee', 'Doctor Fee'), ('Doctor Dues', 'Doctor Dues'), ('Lab Test', 'Lab Test & Diagnostics'), ('Medicine', 'Medicine & Pharmacy Supply'), ('Admission', 'Admission & Hospitalization'), ('Procedure', 'Surgical / Medical Procedure'), ('Hospital Bill', 'Hospital Panel Monthly Bill'), ('Other Medical Expense', 'Other Medical Expense'), ('Administrative Welfare Expense', 'Administrative Welfare Expense')], default='Hospital Bill', max_length=100),
        ),
        migrations.AddField(
            model_name='bill',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Cash', 'Cash'), ('Online', 'Online')], default='Bank Transfer', max_length=50),
        ),
        migrations.AddField(
            model_name='budget',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Probation', 'Probation'), ('Daily Wage', 'Daily Wage'), ('Trainee / Apprentice', 'Trainee / Apprentice')], default='Permanent', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='account',
            field=models.CharField(blank=True, default='Welfare Main Account (HBL)', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='finance/'),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='contact_person',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='attached_document',
            field=models.FileField(blank=True, null=True, upload_to='visits/'),
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='department_specialization',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='total_visit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='medicalclaim',
            name='admission_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='medicalclaim',
            name='claim_type',
            field=models.CharField(choices=[('OPD Consultation', 'OPD Consultation'), ('Emergency Treatment', 'Emergency Treatment'), ('Hospitalization / Surgery', 'Hospitalization / Surgery'), ('Diagnostic / Lab Tests', 'Diagnostic / Lab Tests'), ('Prescription Medicine', 'Prescription Medicine'), ('Maternity / Dental / Optical', 'Maternity / Dental / Optical'), ('Other Medical Claim', 'Other Medical Claim')], default='OPD Consultation', max_length=100),
        ),
        migrations.AddField(
            model_name='medicalclaim',
            name='claimable_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='medicalclaim',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalclaim',
            name='doctor_dues',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='medicalclaim',
            name='doctor_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='medicalclaim',
            name='lab_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='medicalclaim',
            name='medicine_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='medicalclaim',
            name='other_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='medicalclaim',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='medicalclaim',
            name='procedure_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='medicalclaim',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalclaim',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='claims/'),
        ),
        migrations.AddField(
            model_name='medicalclaim',
            name='treatment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='unit',
            field=models.CharField(choices=[('Pack', 'Pack / Box'), ('Bottle', 'Bottle'), ('Strip', 'Strip'), ('Tablet', 'Tablet'), ('Vial', 'Vial / Ampoule'), ('Tube', 'Tube'), ('Piece', 'Piece')], default='Pack', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Unit Cost (Rs.)'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='category',
            field=models.CharField(default='Medicines & Medical Consumables', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='invoice_attachment',
            field=models.FileField(blank=True, null=True, upload_to='procurement/'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='item_name',
            field=models.CharField(default='Medical Consumables', max_length=200),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent / Priority'), ('Emergency', 'Emergency')], default='Normal', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='welfare_app.supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='ntn_registration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NTN / STRN #'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(blank=True, default='Net 30 Days', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='approvalworkflow',
            name='stage',
            field=models.CharField(choices=[('Submitted', 'Submitted for Review'), ('Welfare Review', 'Welfare Officer Review'), ('Manager Approval', 'Factory Manager Approval'), ('Finance Verification', 'Finance & Treasury Verification'), ('Payment', 'Payment Processing'), ('Completed', 'Completed / Disbursed'), ('Rejected', 'Rejected'), ('Returned', 'Returned for Correction')], max_length=50),
        ),
        migrations.AlterField(
            model_name='approvalworkflow',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Returned', 'Returned for Correction')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('Created', 'Created'), ('Updated', 'Updated'), ('Deleted', 'Deleted'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Submitted', 'Submitted'), ('Paid', 'Payment Recorded'), ('Login', 'Login'), ('Logout', 'Logout')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Invoice / Bill #'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('Medical', 'Medical Welfare Fund'), ('Operational', 'Operational Welfare'), ('Emergency', 'Emergency / Critical Health Fund'), ('Pharmacy', 'Pharmacy & Medicine Fund'), ('Other', 'Other Welfare Allocation')], default='Medical', max_length=50),
        ),
        migrations.AlterField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='claimexpenseitem',
            name='category',
            field=models.CharField(choices=[('Doctor Fee', 'Doctor Fee'), ('Doctor Dues', 'Doctor Dues'), ('Laboratory', 'Laboratory / Diagnostic'), ('Medicine', 'Medicine & Pharmacy'), ('Admission', 'Admission / Hospital Stay'), ('Surgery', 'Surgery / Procedure'), ('Other', 'Other Expense')], max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PMC / PMDC Reg #'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, help_text='e.g. Cardiology, Orthopedics, General Physician', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('CNIC', 'CNIC / National Identity Card'), ('Medical Report', 'Medical Report / Discharge Summary'), ('Bill / Invoice', 'Bill / Invoice / Receipt'), ('Prescription', 'Doctor Prescription'), ('Hospital Contract', 'Hospital Panel Contract'), ('Welfare Policy', 'Welfare Policy Document'), ('Other', 'Other Attachment')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cnic',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CNIC'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='father_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Father/Guardian Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='grade_scale',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pay Grade / Scale'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pl_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Employee ID / PL#'),
        ),
        migrations.AlterField(
            model_name='financetransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financetransaction',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Cash', 'Cash'), ('Online', 'Online Banking / RTGS')], default='Bank Transfer', max_length=50),
        ),
        migrations.AlterField(
            model_name='financetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Income', 'Receipt / Allocation (Income)'), ('Expense', 'Disbursement / Expense'), ('Payment', 'Medical Claim Payment'), ('Refund', 'Refund / Credit Note')], max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_type',
            field=models.CharField(choices=[('Government', 'Government Hospital'), ('Private', 'Private Hospital'), ('Semi-Government', 'Semi-Government'), ('Military', 'Military / Armed Forces'), ('Clinic', 'Clinic / Diagnostic Center')], default='Private', max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='panel_status',
            field=models.CharField(choices=[('Panel', 'Panel Hospital (Contracted)'), ('Non-Panel', 'Non-Panel Hospital')], default='Panel', max_length=50),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Completed', 'Completed'), ('Follow-up Required', 'Follow-up Required')], default='Completed', max_length=50),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='visit_type',
            field=models.CharField(choices=[('OPD', 'OPD / Outpatient'), ('Emergency', 'Emergency Room'), ('Admission', 'Hospital Admission / Inpatient'), ('Follow-up', 'Follow-up Consultation'), ('Lab Test', 'Laboratory & Diagnostics'), ('Consultation', 'Specialist Consultation')], default='OPD', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalclaim',
            name='claim_status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Partially Approved', 'Partially Approved'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup / Suspension'), ('Injection', 'Injection / IV Infusion'), ('Cream / Ointment', 'Cream / Ointment'), ('Eye/Ear Drops', 'Eye/Ear Drops'), ('Inhaler', 'Inhaler / Spray'), ('Surgical Supply', 'Surgical Supply / Bandage'), ('Other', 'Other Pharmacy Item')], default='Tablet', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicinetransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PO / Invoice / Rx #'),
        ),
        migrations.AlterField(
            model_name='medicinetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Stock In', 'Stock In (Purchase/Receipt)'), ('Stock Out', 'Stock Out (Dispensed/Issued)'), ('Adjustment', 'Stock Adjustment'), ('Return', 'Return to Supplier')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Info', 'Info'), ('Success', 'Success'), ('Warning', 'Warning'), ('Error', 'Error'), ('Approval', 'Approval Request'), ('Claim', 'Medical Claim'), ('Payment', 'Payment Disbursed'), ('Stock', 'Low Stock Warning'), ('Budget', 'Budget Alert'), ('Contract', 'Hospital Contract Notice')], default='Info', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Ordered', 'Ordered / Issued'), ('Acknowledged', 'Acknowledged by Vendor'), ('Received', 'Received & Stocked'), ('Cancelled', 'Cancelled')], default='Ordered', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Ordered', 'Ordered'), ('Completed', 'Completed')], default='Pending Approval', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin (Full Access)'), ('Welfare Officer', 'Welfare Officer (Claims, Visits, Hospitals, Reports)'), ('HR Staff', 'HR Staff (Employees & HR Reports)'), ('Finance Officer', 'Finance Officer (Payments, Budgets, Treasury, Bills)'), ('Approver', 'Approver (Approvals & Claim Review)'), ('Viewer', 'Viewer (Read-only Access)')], default='Welfare Officer', max_length=50),
        ),
        migrations.CreateModel(
            name='BenefitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('grade_scale', models.CharField(blank=True, help_text='e.g. All Scales, Scale-16+, etc.', max_length=50, null=True)),
                ('annual_medical_limit', models.DecimalField(decimal_places=2, default=100000.0, max_digits=12)),
                ('opd_consultation_limit', models.DecimalField(decimal_places=2, default=3000.0, max_digits=12)),
                ('lab_coverage_percent', models.DecimalField(decimal_places=2, default=100.0, help_text='Percentage covered (0-100)', max_digits=5)),
                ('medicine_coverage_percent', models.DecimalField(decimal_places=2, default=100.0, help_text='Percentage covered (0-100)', max_digits=5)),
                ('room_per_day_limit', models.DecimalField(decimal_places=2, default=6000.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='welfare_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('approved_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('Bank Transfer', 'Bank Transfer / Online'), ('Cheque', 'Bank Cheque'), ('Cash', 'Cash Disbursement'), ('Payroll Credit', 'Payroll Allowance Addition')], default='Bank Transfer', max_length=50)),
                ('account', models.CharField(blank=True, help_text='e.g. Welfare Treasury HBL A/C 0042', max_length=120, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=120, null=True, verbose_name='Tx / Cheque #')),
                ('receipt_attachment', models.FileField(blank=True, null=True, upload_to='payments/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='welfare_app.medicalclaim')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='welfare_app.employee')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
