# Generated by Django 6.1.1 on 2026-09-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0004_alter_bill_options_alter_budget_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Probation', 'Probation'), ('Temporary', 'Temporary'), ('Daily Wage', 'Daily Wage'), ('Intern', 'Intern'), ('Trainee / Apprentice', 'Trainee / Apprentice'), ('Other', 'Other')], default='Permanent', max_length=50),
        ),
    ]
