# Generated by Django 6.1.1 on 2026-09-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0005_alter_employee_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalvisit',
            name='diagnostic_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Diagnostic & Lab Tests Cost'),
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='diagnostic_doc',
            field=models.FileField(blank=True, null=True, upload_to='visits/diagnostic/', verbose_name='Diagnostic / Lab Bill & Report'),
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='doctor_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Consultation Fee / Doctor Fee'),
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='doctor_fee_doc',
            field=models.FileField(blank=True, null=True, upload_to='visits/consultation/', verbose_name='Doctor Fee Slip / Receipt'),
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='medicine_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Medicine Cost'),
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='medicine_doc',
            field=models.FileField(blank=True, null=True, upload_to='visits/medicine/', verbose_name='Medicine Bill / Pharmacy Slip'),
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='other_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Other Hospital Charges / Miscellaneous'),
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='other_charges_doc',
            field=models.FileField(blank=True, null=True, upload_to='visits/other/', verbose_name='Other Charges Invoice / Receipt'),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='attached_document',
            field=models.FileField(blank=True, null=True, upload_to='visits/', verbose_name='General Attached Document'),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='total_visit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Visit Cost'),
        ),
    ]
