# Generated by Django 6.1.1 on 2026-09-21 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0006_hospitalvisit_diagnostic_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Expense Title / Category e.g. Medicine, Lab Test, Doctor Fee', max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('document', models.FileField(blank=True, help_text='Receipt or Document Scan', null=True, upload_to='visits/expenses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='welfare_app.hospitalvisit')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
