# Generated by Django 6.1.1 on 2026-09-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0007_visitexpenseitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='relationship',
            field=models.CharField(choices=[('Spouse', 'Spouse'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Other', 'Other')], max_length=50),
        ),
    ]
