# Generated by Django 6.1.1 on 2026-09-22 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0008_alter_dependent_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Expense description / voucher remark', null=True)),
                ('document', models.FileField(blank=True, help_text='Attached document or receipt', null=True, upload_to='bills/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='welfare_app.bill')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
