# Generated by Django 6.1.1 on 2026-09-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_app', '0009_billdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimexpenseitem',
            name='category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='medicalclaim',
            name='claim_status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Partially Approved', 'Partially Approved'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalclaim',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], default='Unpaid', max_length=50),
        ),
    ]
